[params]
    author = "Chong Chen (陈翀)"
    description = "M.S. Student at [Sun Yat-sen University](https://www.sysu.edu.cn/). Focusing on LLM4SE and Program Analysis."
    motto = "Most things in the world are not that important. But truth and love matter."

[[menu.main]]
    name = 'About Me'
    url = '#about-me'
    weight = 1
[[menu.main]]
    name = 'Educations'
    url = '#educations'
    weight = 2
[[menu.main]]
    name = 'Publications'
    url = '#publications'
    weight = 3
[[menu.main]]
    name = 'Honors and Awards'
    url = '#honors-and-awards'
    weight = 4
[[menu.main]]
    name = 'Academic Service'
    url = '#academic-service'
    weight = 5
[[menu.main]]
    name = 'Contact Me'
    url = '#contact-me'
    weight = 6
