profilePicture = "images/profile.png"
enableDarkMode = true

# Google Analytics ID, leave empty if you don't want to use Google Analytics
googleAnalyticsID = ""

[[social]]
name = "github"
url = "https://github.com/BugmakerCC"
icon = "fab fa-github"

[[social]]
name = "google-scholar"
url = "https://scholar.google.cz/citations?user=1sncT70AAAAJ&hl=zh-CN"
icon = "fab fa-google-scholar"

[[social]]
name = "email"
url = "mailto:chench578@mail2.sysu.edu.cn"
icon = "fas fa-envelope"

[[social]]
name = "wechat"
url = "/chong/images/wechat-qr.jpg"
icon = "fab fa-weixin"
