baseURL = 'https://bugmakercc.github.io/chong/'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

# theme
theme = "zero-academic-page"
themesDir = "../../"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true