baseURL = 'https://bugmakercc.github.io/chong/'
languageCode = 'en-US'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
[[module.imports]]
path = "github.com/geekifan/zero-academic-page"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true